services:
  db:
    image: postgres:14
    restart: on-failure
    container_name: postgres-pj
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./scripts/*.sql:/docker-entrypoint-initdb.d/
volumes:
  pgdata: